trigger:
- main
pool:
 vmImage: 'ubuntu-latest'
steps:
- task: UseJavaVersion@1
 inputs:
   versionSpec: '7'
   checkLatest: true

- task: Maven@4
 inputs:
   mavenPomFile: 'pom.xml'
   goals: 'clean install'
   options: '-Dmaven.test.failure.ignore=true'
   javaHomeOption: 'JDKVersion'
   jdkVersionOption: '7'  #